# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  desc "Generates all profiles we need to work with the app"
  lane :generate_profiles do
    # Main App
    match(type: 'development', app_identifier: 'at.meisterwork.expense.stg', force: true)
    match(type: 'development', app_identifier: 'at.meisterwork.expense', force: true)
    match(type: 'appstore', app_identifier: 'at.meisterwork.expense.stg', force: true)
    match(type: 'appstore', app_identifier: 'at.meisterwork.expense', force: true)
  end
end
